services:
  # Cron Job (월-금 아침 9시 한국 시간 실행, 주말 제외)
  - type: cron
    name: stock-monitor-cron
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.main
    cron: "0 23 * * 0-4"  # 한국 시간 월-금 아침 8시 (UTC 일 23시-목 23시)
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: EMAIL_ENABLED
        value: true
      - key: EMAIL_SENDER
        value: rheehot@gmail.com
      - key: EMAIL_PASSWORD
        value: ncpb ukay lyrz ueaq
      - key: EMAIL_RECIPIENTS
        value: rheehot@gmail.com
      - key: KOSPI_SYMBOL
        value: ^KS11
      - key: KOSDAQ_SYMBOL
        value: ^KQ11
      - key: NASDAQ_SYMBOL
        value: ^IXIC
      - key: SP500_SYMBOL
        value: ^GSPC
      - key: DOW_SYMBOL
        value: ^DJI
      - key: EWY_SYMBOL
        value: EWY
      - key: MU_SYMBOL
        value: MU
      - key: USDKRW_SYMBOL
        value: KRW=X
